### ISSUE TITLE
Rev 3.0.2

### ISSUE THREAD

**Issue by brainsiq** [risaacson/docker-gcd-local#2]
Good work on providing this on the docker hub :sunglasses: 

Are you able to push up another tag with the latest revision - http://storage.googleapis.com/gcd/tools/gcd-v1beta2-rev1-3.0.2.zip

**Comment by risaacson** [comment]
I am waiting for the auto builds to happen and this will be out there.

**Comment by brainsiq** [comment]
Sweet, it's there. Thanks :bow:
